apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-booking
  template:
    metadata:
      labels:
        app: worker-booking
    spec:
      containers:
      - name: worker-booking
        image: haran472/worker-booking:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: worker-booking
        - name: DB_USERNAME
          value: root
        - name: DB_PASSWORD
          value: ""
